import os
import numpy as np
import datetime as dt
from airflow import DAG
from airflow.sdk import task
from airflow.models import Variable

# Import your look-ahead resilient scheduler here
# from your_module import find_greenest_schedule_via_rle

DATA_DIR = "/home/gonca/Carbon_Scheduler/airflow/data/tree_reduction_test/"
os.makedirs(DATA_DIR, exist_ok=True)
ARRAY_SIZE = 5000

WORKFLOW_METADATA = [
    {"id": "generate_leaf__0", "dur": 2, "cores": 2, "depends_on": []},
    {"id": "generate_leaf__1", "dur": 2, "cores": 2, "depends_on": []},
    {"id": "generate_leaf__2", "dur": 1, "cores": 1, "depends_on": []},
    {"id": "generate_leaf__3", "dur": 1, "cores": 1, "depends_on": []},
    {"id": "reduce_branch__0", "dur": 2, "cores": 2, "depends_on": ["generate_leaf__0", "generate_leaf__1"]},
    {"id": "reduce_branch__1", "dur": 1, "cores": 2, "depends_on": ["generate_leaf__2", "generate_leaf__3"]},
    {"id": "final_reduction", "dur": 2, "cores": 1, "depends_on": ["reduce_branch__0", "reduce_branch__1"]}
]

EDGES = [
    ("generate_leaf__0", "reduce_branch__0"),
    ("generate_leaf__1", "reduce_branch__0"),
    ("generate_leaf__2", "reduce_branch__1"),
    ("generate_leaf__3", "reduce_branch__1"),
    ("reduce_branch__0", "final_reduction"),
    ("reduce_branch__1", "final_reduction")
]

default_args = {
    'owner': 'airflow',
    'start_date': dt.datetime(2026, 5, 5),
}

with DAG(
    dag_id="workflow_tree_reduction_carbon",
    default_args=default_args,
    schedule=None,
    catchup=False,
    params={
        "deadline_iso": "2026-06-03T00:00:00" if os.getenv("AIRFLOW_IS_PARSING") else (dt.datetime.now() + dt.timedelta(days=2)).isoformat(),
        "workflow_structure": WORKFLOW_METADATA,
        "edges": EDGES,
        "sla_level": 95
    }
) as dag:

    # -------------------------------------------------------------------------
    # NEW ROOT TASK: COMPUTES THE COHESIVE PLAN ONCE
    # -------------------------------------------------------------------------
    @task(task_id="carbon_planner")
    def carbon_planner(dag_run=None, **context):
        # 1. Gather all inputs needed by your scheduler
        # REGIONS = [...]
        # rle_index = [...]
        # all_regions_intensities = [...]
        
        # 2. Run the full validation/resilient engine once for the tree
        # global_manifest = find_greenest_schedule_via_rle(
        #     REGIONS, WORKFLOW_METADATA, all_regions_intensities, rle_index,
        #     dag_run.logical_date, max_window_hours=72, base_ci=400
        # )
        
        # Mocking look-ahead manifest map for demonstration:
        global_manifest = {
            "generate_leaf__0": {"start": "2026-06-08T15:00:00", "region": "DE"},
            "generate_leaf__1": {"start": "2026-06-08T15:00:00", "region": "DE"},
            "generate_leaf__2": {"start": "2026-06-08T17:00:00", "region": "DE"},
            "generate_leaf__3": {"start": "2026-06-08T17:00:00", "region": "DE"},
            "reduce_branch__0": {"start": "2026-06-08T18:00:00", "region": "DE"},
            "reduce_branch__1": {"start": "2026-06-08T19:00:00", "region": "DE"},
            "final_reduction":  {"start": "2026-06-08T21:00:00", "region": "DE"},
        }
        return global_manifest

    # -------------------------------------------------------------------------
    # EXECUTION WORKERS
    # -------------------------------------------------------------------------
    @task
    def generate_leaf(leaf_id: int, seed_val: float, task_instance=None, dag_run=None):
        # Fetch the shared, cohesive manifest generated by the root planner task
        manifest = task_instance.xcom_pull(task_ids="carbon_planner")
        my_schedule = manifest.get(task_instance.task_id)
        
        # Optional: insert execution delay/deferred check until target ISO timestamp is reached
        print(f"Executing {task_instance.task_id} in region {my_schedule['region']} scheduled at {my_schedule['start']}")
        
        run_id = dag_run.run_id
        path = os.path.join(DATA_DIR, run_id)
        os.makedirs(path, exist_ok=True)
        
        arr = np.linspace(seed_val, seed_val + 10.0, ARRAY_SIZE, dtype=np.float64)
        f_path = os.path.join(path, f"leaf_{leaf_id}.npy")
        np.save(f_path, arr)
        return f_path

    @task
    def reduce_branch(branch_id: int, leaf_a_path: str, leaf_b_path: str, task_instance=None, dag_run=None):
        manifest = task_instance.xcom_pull(task_ids="carbon_planner")
        my_schedule = manifest.get(task_instance.task_id)
        print(f"Executing {task_instance.task_id} in region {my_schedule['region']} scheduled at {my_schedule['start']}")
        
        run_id = dag_run.run_id
        path = os.path.join(DATA_DIR, run_id)
        
        matrix_a = np.load(leaf_a_path)
        matrix_b = np.load(leaf_b_path)
        
        combined = np.sqrt((matrix_a ** 2) + (matrix_b ** 2))
        f_path = os.path.join(path, f"branch_{branch_id}.npy")
        np.save(f_path, combined)
        return f_path

    @task(task_id="final_reduction")
    def final_reduction(branch_a_path: str, branch_b_path: str, task_instance=None, dag_run=None):
        manifest = task_instance.xcom_pull(task_ids="carbon_planner")
        my_schedule = manifest.get(task_instance.task_id)
        print(f"Executing final_reduction in region {my_schedule['region']} scheduled at {my_schedule['start']}")
        
        run_id = dag_run.run_id
        path = os.path.join(DATA_DIR, run_id)
        
        branch_a = np.load(branch_a_path)
        branch_b = np.load(branch_b_path)
        
        final_vector = branch_a - branch_b
        norm_val = float(np.linalg.norm(final_vector))
        
        final_out = os.path.join(path, "final_tree_result.npy")
        np.save(final_out, final_vector)
        return {"path": final_out, "norm": norm_val}

    # --- SET UP PIPELINE RELATIONSHIPS ---
    planner = carbon_planner()

    l0 = generate_leaf.override(task_id="generate_leaf__0")(0, 1.5)
    l1 = generate_leaf.override(task_id="generate_leaf__1")(1, 2.5)
    l2 = generate_leaf.override(task_id="generate_leaf__2")(2, 3.5)
    l3 = generate_leaf.override(task_id="generate_leaf__3")(3, 4.5)

    # Force leaves to wait until the single plan is computed
    planner >> [l0, l1, l2, l3]

    b0 = reduce_branch.override(task_id="reduce_branch__0")(0, l0, l1)
    b1 = reduce_branch.override(task_id="reduce_branch__1")(1, l2, l3)

    final_result = final_reduction(b0, b1)